name: Create Dev Test and Prod Environments
# clean up the environment for the next demo
# clean up environment tasks for QA and Prod 

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: 'Name for the environment to be created'
        required: true
        default: '107 Aykut' # Default value, change as needed
      client_id: 
        description: 'Service principal client id'
        required: true
        default: '3d50fc54-97a3-40d1-b976-ef0af2206189' # Deine Client-ID
      user_id: 
        description: 'AAD object id for the user'
        required: true
        default: '707f9714-00fd-4939-95ac-4cb3f931ad00' # Replace with default value or leave as placeholder

# Do Not change these values

jobs:
  Create-Environments:
    runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Create Developer Environment
      uses: microsoft/powerplatform-actions/create-environment@v0
      with:
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.POWERPLATFORMSPN }}
        tenant-id: ${{ secrets.TENANT_ID }}
        name: ${{ github.event.inputs.env_name }}_Dev
        type: Developer
        domain: ${{ github.event.inputs.env_name }}Dev
        region: germanywestcentral   # Region auf Deutschland setzen
        language: de                 # Sprache auf Deutsch setzen

    - name: assign-user to developer environment
      uses: microsoft/powerplatform-actions/assign-user@v0
      with:
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.POWERPLATFORMSPN }}
        tenant-id: ${{ secrets.TENANT_ID }}
        environment: 'https://${{ github.event.inputs.env_name }}Dev.dynamics.com'
        user: ${{ github.event.inputs.user_id }}
        role: System Administrator

    - name: Create Test Environment
      uses: microsoft/powerplatform-actions/create-environment@v0
      with:
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.POWERPLATFORMSPN }}
        tenant-id: ${{ secrets.TENANT_ID }}
        name: ${{ github.event.inputs.env_name }}_Test
        type: Sandbox
        domain: ${{ github.event.inputs.env_name }}Test
        region: germanywestcentral   # Region auf Deutschland setzen
        language: de                 # Sprache auf Deutsch setzen

    - name: assign-user to test environment
      uses: microsoft/powerplatform-actions/assign-user@v0
      with:
        app-id: ${{ secrets.CLIENT_ID }}
        client
