- name: Create Developer Environment
  uses: microsoft/powerplatform-actions/create-environment@v0
  with:
    app-id: ${{ secrets.CLIENT_ID }}
    client-secret: ${{ secrets.POWERPLATFORMSPN }}
    tenant-id: ${{ secrets.TENANT_ID }}
    name: ${{ github.event.inputs.env_name }}_Dev
    type: Developer
    domain: ${{ github.event.inputs.env_name.replace(' ', '-') }}Dev

- name: assign-user to developer environment
  uses: microsoft/powerplatform-actions/assign-user@v0
  with:
    app-id: ${{ secrets.CLIENT_ID }}
    client-secret: ${{ secrets.POWERPLATFORMSPN }}
    tenant-id: ${{ secrets.TENANT_ID }}
    environment: 'https://${{ github.event.inputs.env_name.replace(' ', '-') }}Dev.dynamics.com'
    user: ${{ github.event.inputs.user_id }}
    role: System Administrator

- name: Create Test Environment
  uses: microsoft/powerplatform-actions/create-environment@v0
  with:
    app-id: ${{ secrets.CLIENT_ID }}
    client-secret: ${{ secrets.POWERPLATFORMSPN }}
    tenant-id: ${{ secrets.TENANT_ID }}
    name: ${{ github.event.inputs.env_name }}_Test
    type: Sandbox
    domain: ${{ github.event.inputs.env_name.replace(' ', '-') }}Test

- name: assign-user to test environment
  uses: microsoft/powerplatform-actions/assign-user@v0
  with:
    app-id: ${{ secrets.CLIENT_ID }}
    client-secret: ${{ secrets.POWERPLATFORMSPN }}
    tenant-id: ${{ secrets.TENANT_ID }}
    environment: 'https://${{ github.event.inputs.env_name.replace(' ', '-') }}Test.crm.dynamics.com'
    user: ${{ github.event.inputs.user_id }}
    role: System Administrator

- name: Create Production Environment
  uses: microsoft/powerplatform-actions/create-environment@v0
  with:
    app-id: ${{ secrets.CLIENT_ID }}
    client-secret: ${{ secrets.POWERPLATFORMSPN }}
    tenant-id: ${{ secrets.TENANT_ID }}
    name: ${{ github.event.inputs.env_name }}_Prod
    type: Production
    domain: ${{ github.event.inputs.env_name.replace(' ', '-') }}Prod

- name: assign-user to Prod environment
  uses: microsoft/powerplatform-actions/assign-user@v0
  with:
    app-id: ${{ secrets.CLIENT_ID }}
    client-secret: ${{ secrets.POWERPLATFORMSPN }}
    tenant-id: ${{ secrets.TENANT_ID }}
    environment: 'https://${{ github.event.inputs.env_name.replace(' ', '-') }}Prod.crm.dynamics.com'
    user: ${{ github.event.inputs.user_id }}
    role: System Administrator
