name: Create Dev Test and Prod Environments
# clean up the environment for the next demo
# clean up environment tasks for QA and Prod 

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: 'Name for the environment to be created'
        required: true
        default: '107 Aykut' # Default value, change as needed
      client_id: 
        description: 'Service principal client id'
        required: true
        default: '3d50fc54-97a3-40d1-b976-ef0af2206189' # Deine Client-ID
      user_id: 
        description: 'AAD object id for the user'
        required: true
        default: '707f9714-00fd-4939-95ac-4cb3f931ad00' # Replace with default value or leave as placeholder

# Do Not change these values

jobs:
  Create-Environments:
    runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps
