name: Create Dev Test and Prod Environments

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: 'Name for the environment to be created'
        required: true
        default: 'TestAykut' # Default value, change as needed
      client_id: 
        description: 'Service principal client id'
        required: true
        default: '3d50fc54-97a3-40d1-b976-ef0af2206189' # Deine Client-ID
      user_id: 
        description: 'AAD object id for the user'
        required: true
        default: '707f9714-00fd-4939-95ac-4cb3f931ad00' # Replace with default value or leave as placeholder

jobs:
  Create-Environments:
    runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    # Sleep for 30 seconds before attempting the next action download
    - name: Sleep before downloading PowerPlatform Actions
      run: |
        echo "Waiting for 30 seconds before proceeding with the next step."
        sleep 30

    # Retry the download of the PowerPlatform Actions after waiting
    - name: Create Developer Environment
      uses: microsoft/powerplatform-actions/create-environment@v0
      with:
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.POWERPLATFORMSPN }}
        tenant-id: ${{ secrets.TENANT_ID }}
        name: ${{ github.event.inputs.env_name }}_Dev
        type: Developer
        domain: ${{ github.event.inputs.env_name }}Dev

    - name: assign-user to developer environment
      uses: microsoft/powerplatform-actions/assign-user@v0
      with:
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.POWERPLATFORMSPN }}
        tenant-id: ${{ secrets.TENANT_ID }}
        environment: 'https://${{ github.event.inputs.env_name }}Dev.dynamics.com'
        user: ${{ github.event.inputs.user_id }}
        role: System Administrator

    # Repeat the process for other environments as needed, each with a sleep delay
    - name: Sleep before creating Test Environment
      run: |
        echo "Waiting for 30 seconds before creating the test environment."
        sleep 30

    - name: Create Test Environment
      uses: microsoft/powerplatform-actions/create-environment@v0
      with:
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.POWERPLATFORMSPN }}
        tenant-id: ${{ secrets.TENANT_ID }}
        name: ${{ github.event.inputs.env_name }}_Test
        type: Sandbox
        domain: ${{ github.event.inputs.env_name }}Test

    - name: assign-user to test environment
      uses: microsoft/powerplatform-actions/assign-user@v0
      with:
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.POWERPLATFORMSPN }}
        tenant-id: ${{ secrets.TENANT_ID }}
        environment: 'https://${{ github.event.inputs.env_name }}Test.crm.dynamics.com'
        user: ${{ github.event.inputs.user_id }}
        role: System Administrator

    # Another sleep before creating the production environment
    - name: Sleep before creating Production Environment
      run: |
        echo "Waiting for 30 seconds before creating the production environment."
        sleep 30

    - name: Create Production Environment
      uses: microsoft/powerplatform-actions/create-environment@v0
      with:
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.POWERPLATFORMSPN }}
        tenant-id: ${{ secrets.TENANT_ID }}
        name: ${{ github.event.inputs.env_name }}_Prod
        type: Production
        domain: ${{ github.event.inputs.env_name }}Prod

    - name: assign-user to Prod environment
      uses: microsoft/powerplatform-actions/assign-user@v0
      with:
        app-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.POWERPLATFORMSPN }}
        tenant-id: ${{ secrets.TENANT_ID }}
        environment: 'https://${{ github.event.inputs.env_name }}Prod.crm.dynamics.com'
        user: ${{ github.event.inputs.user_id }}
        role: System Administrator
